baseURL = 'https://imiron-io.github.io/'
languageCode = 'en-us'
title = 'Imiron'
theme = 'custom'

[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = 'Blog'
    url = '/blog/'
    weight = 2
