title = "Imiron"
baseURL = "https://imiron-io.github.io/"
languageCode = "en-US"
theme = "ananke"

DefaultContentLanguage = "ja"
SectionPagesMenu = "main"
pagination.pagerSize = 10
# googleAnalytics = "" # TODO
enableRobotsTXT = true
Copyright = "Imiron Co., Ltd. All Rights Reserved"

[markup.goldmark.renderer]
unsafe= true

[languages]
  [languages.en]
  title = "Imiron"
  contentDir = "content/en"
  languageName = "EN"
  languageCode = "en-US"
  # languageDirection = 'rtl' for Right-To-Left languages
  [languages.ja]
  title = "Imiron"
  contentDir = "content/ja"
  languageName = "JP"
  languageCode = "ja-JP"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
author = "Imiron Co., Ltd."
omit_header_text = true
favicon = "images/imiron_favicon.png"
site_logo = "images/imiron_logo.png"
description = "Imiron website" # TODO
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-dark-gray"
recent_posts_number = 3
date_format = ":date_full"
# choose fitting and alignment styles for the featured image using Tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
featured_image_class = "cover bg-bottom"
# choose a color dimming class for the page or site header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
# cover_dimming_class = "bg-black-10"


# [[params.ananke_socials]]
# name = "twitter"
# url = "https://twitter.com/GoHugoIO"

custom_css = ["custom.css"]

[params.ananke.social.share]
networks = [
  "linkedin"
]

[params.ananke.social.follow]
networks = [
  "linkedin"
]

[params.ananke.social.linkedin]
username = "imiron"
