title = "Imiron"
baseURL = "https://imiron-io.github.io/"
languageCode = "ja-JP"
theme = "imi"

defaultContentLanguage = "ja"
SectionPagesMenu = "main"
pagination.pagerSize = 10
# googleAnalytics = "" # TODO
enableRobotsTXT = true
Copyright = "Imiron Co., Ltd. All Rights Reserved."

[markup.goldmark.renderer]
unsafe= true

[languages]
  [languages.en]
  title = "Imiron"
  contentDir = "content/en"
  languageName = "EN"
  languageCode = "en-US"
  # languageDirection = 'rtl' for Right-To-Left languages
  [languages.en.menus]
#      [[languages.en.menus.main]]
#        name = "HOME"
#        pageRef = '/'
#        weight = -500
      [[languages.en.menus.main]]
        name = "Career"
        pageRef = '/career'
        weight = -400
      [[languages.en.menus.main]]
        name = "News"
        pageRef = '/tags/press-release'
        weight = 200
      [[languages.en.menus.main]]
        name = "Blog"
        pageRef = '/tags/tech-blog'
        weight = 300
      [[languages.en.menus.main]]
        name = "About"
        pageRef = '/about'
        weight = 400
      [[languages.en.menus.main]]
        name = "Company"
        pageRef = '/company'
        weight = 500
  [languages.ja]
  title = "Imiron"
  contentDir = "content/ja"
  languageName = "JP"
  languageCode = "ja-JP"
  [languages.ja.menus]
#      [[languages.ja.menus.main]]
#        name = "HOME"
#        pageRef = '/'
#        weight = -500
      [[languages.ja.menus.main]]
        name = "Career"
        pageRef = '/career'
        weight = -400
      [[languages.ja.menus.main]]
        name = "News"
        pageRef = '/tags/press-release'
        weight = 200
      [[languages.ja.menus.main]]
        name = "Blog"
        pageRef = '/tags/tech-blog'
        weight = 300
      [[languages.ja.menus.main]]
        name = "About"
        pageRef = '/about'
        weight = 400
      [[languages.ja.menus.main]]
        name = "Company"
        pageRef = '/company'
        weight = 500

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
body_classes = "avenir bg-light-gray"
text_color = "dark-gray"
author = "Imiron Co., Ltd."
omit_header_text = true
favicon = "images/imiron_favicon.png"
site_logo = "images/imiron_logo.png"
description = "Imiron website" # TODO
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-dark-gray"
recent_posts_number = 10
date_format = ":date_full"
# choose fitting and alignment styles for the featured image using Tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
featured_image_class = "cover bg-bottom"
# choose a color dimming class for the page or site header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
cover_dimming_class = "bg-black-30"


# [[params.ananke_socials]]
# name = "twitter"
# url = "https://twitter.com/GoHugoIO"

custom_css = ["custom.css"]

[params.ananke.social.share]
networks = [
  "linkedin"
]

[params.ananke.social.follow]
networks = [
  "linkedin"
]

[params.ananke.social.linkedin]
profilelink = "https://www.linkedin.com/company/imiron/"
