title = "Imiron"
baseURL = "https://imiron-io.github.io/"
languageCode = "en-US"
theme = "imi"

defaultContentLanguage = "en"
SectionPagesMenu = "main"
pagination.pagerSize = 10
# googleAnalytics = "" # TODO
enableRobotsTXT = true
Copyright = "Imiron Co., Ltd. All Rights Reserved."

[markup.goldmark.renderer]
unsafe= true

[languages]
  [languages.en]
  title = "Imiron"
  contentDir = "content/en"
  languageName = "EN"
  languageCode = "en-US"
  # languageDirection = 'rtl' for Right-To-Left languages
  [languages.en.menus]
#      [[languages.en.menus.main]]
#        name = "HOME"
#        pageRef = '/'
#        weight = -500
      [[languages.en.menus.main]]
        name = "Career"
        pageRef = '/career'
        weight = -400
      [[languages.en.menus.main]]
        name = "News"
        pageRef = '/tags/press-release'
        weight = 200
      [[languages.en.menus.main]]
        name = "Blog"
        pageRef = '/tags/tech-blog'
        weight = 300
      [[languages.en.menus.main]]
        name = "About"
        pageRef = '/about'
        weight = 400
      [[languages.en.menus.main]]
        name = "Company"
        pageRef = '/company'
        weight = 500
  [languages.ja]
  title = "Imiron"
  contentDir = "content/ja"
  languageName = "JP"
  languageCode = "ja-JP"
  [languages.ja.menus]
#      [[languages.ja.menus.main]]
#        name = "HOME"
#        pageRef = '/'
#        weight = -500
      [[languages.ja.menus.main]]
        name = "Career"
        pageRef = '/career'
        weight = -400
      [[languages.ja.menus.main]]
        name = "News"
        pageRef = '/tags/press-release'
        weight = 200
      [[languages.ja.menus.main]]
        name = "Blog"
        pageRef = '/tags/tech-blog'
        weight = 300
      [[languages.ja.menus.main]]
        name = "About"
        pageRef = '/about'
        weight = 400
      [[languages.ja.menus.main]]
        name = "Company"
        pageRef = '/company'
        weight = 500

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
author = "Imiron Co., Ltd."
omit_header_text = true
favicon = "images/imiron_favicon.png"
site_logo = "images/imiron_logo.png"
description = "Imiron website" # TODO
recent_posts_number = 10
date_format = ":date_full"
