title = "Imiron"
baseURL = "https://imiron-io.github.io/"
languageCode = "en-us"
theme = "ananke"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10
# googleAnalytics = "" # TODO
enableRobotsTXT = true
Copyright = "Imiron Co., Ltd. All Rights Reserved"

[markup.goldmark.renderer]
unsafe= true

[languages]
  [languages.en]
  title = "Imiron"
  weight = 1
  contentDir = "content/en"
  # languageDirection = 'rtl' for Right-To-Left languages
  [languages.jp]
  title = "Imiron"
  weight = 2
  contentDir = "content/jp"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
author = ""
favicon = ""
site_logo = ""
description = "Imiron is a startup." # TODO
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
recent_posts_number = 3
date_format = ":date_full"

# [[params.ananke_socials]]
# name = "twitter"
# url = "https://twitter.com/GoHugoIO"
